name: Build and deploy to netlify
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build
        run: |
          sudo apt update
          sudo apt install snapd
          sudo snap install --edge zola
          zola build
      - name: setup node js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: deploy to netlify
        run: npx netlify-cli deploy --dir=./public --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
